Traceback (most recent call last):
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 30, in <module>
    conn = cx_Oracle.connect('oddeye/1234@15.164.247.135:1522/MODB')
cx_Oracle.DatabaseError: ORA-12541: TNS:no listener
-------------------------------------------------------
Starting PROCESS 1: Fetching item info
-------------------------------------------------------
None
Traceback (most recent call last):
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 339, in <module>
    new_filepath = get_products2(category_dict, args.filepath)
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 208, in get_products2
    existing = json.load(data_file)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
-------------------------------------------------------
Starting PROCESS 1: Fetching item info
-------------------------------------------------------
None
Traceback (most recent call last):
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 339, in <module>
    new_filepath = get_products2(category_dict, args.filepath)
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 208, in get_products2
    existing = json.load(data_file)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 256 (char 255)
-------------------------------------------------------
Starting PROCESS 1: Fetching item info
-------------------------------------------------------
None
Traceback (most recent call last):
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 339, in <module>
    new_filepath = get_products2(category_dict, args.filepath)
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 208, in get_products2
    existing = json.load(data_file)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 256 (char 255)
-------------------------------------------------------
Starting PROCESS 1: Fetching item info
-------------------------------------------------------
None
Traceback (most recent call last):
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 339, in <module>
    new_filepath = get_products2(category_dict, args.filepath)
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 211, in get_products2
    newest_product_id = sorted(product_ids, key=lambda x: str(x), reverse=True)[0]   #기존 파일에서 가장 최신 상품의 product_id
IndexError: list index out of range
-------------------------------------------------------
Starting PROCESS 1: Fetching item info
-------------------------------------------------------
None
Traceback (most recent call last):
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 339, in <module>
    new_filepath = get_products2(category_dict, args.filepath)
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 208, in get_products2
    existing = json.load(data_file)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
-------------------------------------------------------
Starting PROCESS 1: Fetching item info
-------------------------------------------------------
None
Traceback (most recent call last):
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 339, in <module>
    new_filepath = get_products2(category_dict, args.filepath)
  File "/root/Personal_Shopper-KJH-KIDS/crawler/THISONE_download_seoulstore.py", line 208, in get_products2
    existing = json.load(data_file)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 4 (char 3)
